name: Deployment pipeline

env:
  MERGE_OR_PUSH_TO_MAIN: ${{ github.event_name == 'push' }}
  SKIP_DEPLOYMENT: ${{ contains(join(github.event.commits.*.message, ', '), '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci
          cd ..

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build:ui

      - name: Start app for tests
        run: npm run start:test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: E2E tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
