name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install
          cd frontend && npm install
          cd ..

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build:ui
